import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Buttons from "../components/Buttons";
import VisibleTaskList from "../components/Table";
import { useState } from "react";



export default function Home({tasks,actions}) {
  const [showTable, setShowTable] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Buttons showTable={showTable} setShowTable={setShowTable}></Buttons>
        {showTable ? <VisibleTaskList></VisibleTaskList> : <></>}
      </main>
    </>
  );
}
