import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Buttons from "../components/Buttons";
import Table from "../components/Table";
import { useState } from "react";

export default function Home() {
  const [showTable, setShowTable] = useState(false);
  const [selectedRows, setSelectedRows] = useState([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Buttons showTable={showTable} setShowTable={setShowTable} selectedRows={selectedRows}></Buttons>
        {showTable ? <Table selectedRows={selectedRows} setSelectedRows={setSelectedRows}></Table> : <></>}
      </main>
    </>
  );
}
